language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt

before_script:
  - export APP_SECRET_KEY="something"

script: 
  - python -m pytest
  - coverage run --source app -m pytest
  - python -m coverage report -m




after_success:
  - coveralls

