"""handles all operations for creating and fetching data relating to sales"""
from flask import request
from flask_jwt_extended import get_jwt_identity

from app.v1.models.model_products import products, check_if_product_exists

# List to store all sales
sales = []

def check_for_quantity_of_product(item):
    """
    Checks for the quantity in the db against that ordered
    If the amount order is more than in stock return True, else return False
    """
    product = [product for product in products if product['quantity'] < item]
    if product:
        return True
    return False

class Sales():
    """Class to handle creating and fetching sales"""
    def make_sale(self, product, quantity, price):
        """Method to hande creation of sales"""
        product = request.json.get('product', None)
        quantity = request.json.get('quantity', None)
        price = request.json.get('price', None)

        # Get info regarding the user from the token
        current_user = get_jwt_identity() 

        # Checks if the product exists
        result = check_if_product_exists(product)
        if not result:
            return {'msg':'item does not exist'}, 404
        
        # Checks the amount ordered against that in stock
        amount = check_for_quantity_of_product(quantity)
        if amount:
            return {'msg':'You cannot order more than what is in stock'}, 400
        
        # Finds the total cost for the transaction
        total_cost = price * quantity

        # Add the sale to the sales list
        sales_dict = {
            "id" : len(sales) + 1,
            "name" : product,
            "quantity" : quantity,
            "price" : price,
            "user_id": current_user['id'],
            "total" : total_cost
        }
        sales.append(sales_dict)
        return {'sale': sales_dict}, 201
    
    def get_all_sales(self):
        """Method to fetch all sales"""
        if len(sales) == 0:
            return {'msg':'No sales made yet'}, 404
        return {'sales':sales}

    def get_one_sale(self, sale_id):
        """Method to fetch a single sale"""
        # Get info regarding the user from the token
        current_user = get_jwt_identity()
        
        # Check if the sale exists
        individual_sale = [sale for sale in sales if sale['id'] == sale_id]
        if not individual_sale:
            return {'msg':'Sale record not found'}, 404

        # Check if the user is an admin
        if current_user['admin'] == True:
           return {'sale record':individual_sale}, 200 

        # Check who generated the sale
        sale = [sale for sale in sales if sale['user_id'] == current_user['id'] and sale['id'] == sale_id]
        if not sale:
            return {'msg':'Sorry, this sale was not generated by you'}, 403
        return {'sale record':sale}, 200

